// Generated by gencpp from file traffic_light_pkg/traffic_light.msg
// DO NOT EDIT!


#ifndef TRAFFIC_LIGHT_PKG_MESSAGE_TRAFFIC_LIGHT_H
#define TRAFFIC_LIGHT_PKG_MESSAGE_TRAFFIC_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traffic_light_pkg
{
template <class ContainerAllocator>
struct traffic_light_
{
  typedef traffic_light_<ContainerAllocator> Type;

  traffic_light_()
    : id(0)
    , state(0)  {
    }
  traffic_light_(const ContainerAllocator& _alloc)
    : id(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::traffic_light_pkg::traffic_light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_light_pkg::traffic_light_<ContainerAllocator> const> ConstPtr;

}; // struct traffic_light_

typedef ::traffic_light_pkg::traffic_light_<std::allocator<void> > traffic_light;

typedef boost::shared_ptr< ::traffic_light_pkg::traffic_light > traffic_lightPtr;
typedef boost::shared_ptr< ::traffic_light_pkg::traffic_light const> traffic_lightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_light_pkg::traffic_light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traffic_light_pkg::traffic_light_<ContainerAllocator1> & lhs, const ::traffic_light_pkg::traffic_light_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traffic_light_pkg::traffic_light_<ContainerAllocator1> & lhs, const ::traffic_light_pkg::traffic_light_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traffic_light_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_pkg::traffic_light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light_pkg::traffic_light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_pkg::traffic_light_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9df1e2ca2c0390fc1af4aa647e41b61";
  }

  static const char* value(const ::traffic_light_pkg::traffic_light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9df1e2ca2c0390fULL;
  static const uint64_t static_value2 = 0xc1af4aa647e41b61ULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_light_pkg/traffic_light";
  }

  static const char* value(const ::traffic_light_pkg::traffic_light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n"
"int8 state\n"
;
  }

  static const char* value(const ::traffic_light_pkg::traffic_light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traffic_light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_light_pkg::traffic_light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_light_pkg::traffic_light_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_LIGHT_PKG_MESSAGE_TRAFFIC_LIGHT_H
