// Generated by gencpp from file car_plugin/Response.msg
// DO NOT EDIT!


#ifndef CAR_PLUGIN_MESSAGE_RESPONSE_H
#define CAR_PLUGIN_MESSAGE_RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <car_plugin/Key.h>

namespace car_plugin
{
template <class ContainerAllocator>
struct Response_
{
  typedef Response_<ContainerAllocator> Type;

  Response_()
    : key()
    , response()  {
    }
  Response_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::car_plugin::Key_<ContainerAllocator>  _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::car_plugin::Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_plugin::Response_<ContainerAllocator> const> ConstPtr;

}; // struct Response_

typedef ::car_plugin::Response_<std::allocator<void> > Response;

typedef boost::shared_ptr< ::car_plugin::Response > ResponsePtr;
typedef boost::shared_ptr< ::car_plugin::Response const> ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_plugin::Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_plugin::Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_plugin::Response_<ContainerAllocator1> & lhs, const ::car_plugin::Response_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_plugin::Response_<ContainerAllocator1> & lhs, const ::car_plugin::Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::car_plugin::Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_plugin::Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_plugin::Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_plugin::Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_plugin::Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_plugin::Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_plugin::Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62068c192be1c92f944918b622366c47";
  }

  static const char* value(const ::car_plugin::Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62068c192be1c92fULL;
  static const uint64_t static_value2 = 0x944918b622366c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_plugin::Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_plugin/Response";
  }

  static const char* value(const ::car_plugin::Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_plugin::Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Key key\n"
"string response\n"
"================================================================================\n"
"MSG: car_plugin/Key\n"
"# Message constabt field to describe the key values\n"
"uint8 UNKNOWN=0\n"
"uint8 MOVE=1\n"
"uint8 BRAKE=2\n"
"# Message field \n"
"uint8 v\n"
;
  }

  static const char* value(const ::car_plugin::Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_plugin::Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_plugin::Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_plugin::Response_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    s << std::endl;
    Printer< ::car_plugin::Key_<ContainerAllocator> >::stream(s, indent + "  ", v.key);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_PLUGIN_MESSAGE_RESPONSE_H
